repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''exec 'source ' . g:rc_dir . '/settings/coc-vim.vim' '''

[[plugins]]
repo = 'tiagovla/tokyodark.nvim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
